const appname = "Pawsome Community";
const appversion = "Version 1.0.0";
const credits = "@abc";
const email = "Email";
const emailHint = "Enter your email";
const password = "Password";
const passwordHint = "*********";
const ConfirmPassword = "Confirm Password ";
const Name = "Name";
const NameHint = "Enter your name";
const forgetPass = "Forget Password";
const login = "Log in";
const logout = "Log out";
const Signup = "Sign up";
const createNewAccount = 'Don’t have an account?';
const loginWith = "Login with";
const privacyPolicy = "Privacy Policy";
const loggedin = "Logged in successfully";
const loggedout = "Logged out successfully";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have account ?";
const resetPass = "Reset Password";
const newpassword = "New password";

// home screen
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
