// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK0xLZhJHsuVGcawSvqmqK7JqkAdHP7zM',
    appId: '1:41141333388:web:8e2f39f49f66200fb4baa9',
    messagingSenderId: '41141333388',
    projectId: 'community-flutter-project',
    authDomain: 'community-flutter-project.firebaseapp.com',
    storageBucket: 'community-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwgc-0oR6134VUPB8NoXmusVl3mh9ewA',
    appId: '1:41141333388:android:949d11189e0c9c82b4baa9',
    messagingSenderId: '41141333388',
    projectId: 'community-flutter-project',
    storageBucket: 'community-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeIdcrj9JGa2-RWwyX6LF3-jOn_2_cexw',
    appId: '1:41141333388:ios:ab650d5ffe9b41b7b4baa9',
    messagingSenderId: '41141333388',
    projectId: 'community-flutter-project',
    storageBucket: 'community-flutter-project.appspot.com',
    iosBundleId: 'com.example.pawsomcommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeIdcrj9JGa2-RWwyX6LF3-jOn_2_cexw',
    appId: '1:41141333388:ios:e55cb0bf07a14c15b4baa9',
    messagingSenderId: '41141333388',
    projectId: 'community-flutter-project',
    storageBucket: 'community-flutter-project.appspot.com',
    iosBundleId: 'com.example.pawsomcommunity.RunnerTests',
  );
}
